stages:
  - byte-compile
  - test
  - artifact

variables:
  VERSION: "0.7.6"
  PKG: "maxima-${VERSION}.tar.gz"

default:
  before_script:
    - apt-get update && apt-get install -y make


byte-compile:27.2:
  stage: byte-compile
  image: silex/emacs:27.2
  cache:
    policy: pull
  script:
    - make compile-test

test:27.2:
  stage: test
  image: silex/emacs:27.2
  cache:
    policy: pull
  before_script:
    - apt-get update && apt-get install -y make maxima
  script:
    - make test

lint:27.2:
  stage: test
  image: silex/emacs:27.2
  cache:
    policy: pull
  script:
    - make lint

test:26.3:
  stage: test
  image: silex/emacs:26.3
  cache:
    policy: pull
  before_script:
    - apt-get update && apt-get install -y make maxima
  script:
    - make test

lint:26.3:
  stage: test
  image: silex/emacs:26.3
  cache:
    policy: pull
  script:
    - make lint

artifact:
  stage: artifact
  image: silex/emacs:27.2
  cache:
    policy: pull
  script:
    - make package
  artifacts:
    paths:
      - $PKG
    expire_in: 1 week
